### ISSUE TITLE
Variable defined in `.env` is not resolved in nested action parameters

### ISSUE THREAD

**Issue by marcinczeczko** [adobe/aio-cli-plugin-app#299]
**Describe the bug**
If any custom variable defined in `.env` is used in the `manifest.yml` in the action input nested parameter it's not being resolved after deploy.

**To Reproduce**
1. Create an app, `aio app init` with just an Generic action
2. Define in the `.env` file a variable `BAR_VAR=lorem-ipsum`
3. Modify manifest.yml for the action as follows
```yaml
sample:
        function: actions/sample/index.js
        web: 'yes'
        runtime: 'nodejs:12'
        inputs:
          foo: $BAR_VAR
          config:
            nestedFoo: $BAR_VAR
```
4. Use simple action code that just returns all the params
```
async function main (params) {
  return {
    statusCode: 200,
    body: params
  }
}

exports.main = main
```
5. Deploy action `aio app deploy --action=sample`
6. Call the action URL, and observe that the `config.nextedFoo` object in the response is not resolved
```
    "config": {
        "nestedFoo": "$BAR_VAR"
    },
    "foo": "lorem-ipsum"
```

**Expected behavior**
- Response object should consists my input params (among other ow fields)
```
    "config": {
        "nestedFoo": "lorem-ipsum"
    },
    "foo": "lorem-ipsum"
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
AIO version: `@adobe/aio-cli/3.7.0 darwin-x64 node-v10.22.1`
Plugins:
```
@adobe/aio-cli-plugin-app 4.0.0
@adobe/aio-cli-plugin-info 1.1.1
```
