### ISSUE TITLE
Show apis if any in manifest.yml on deployment

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-cli-plugin-app#33]
**Is your feature request related to a problem? Please describe.**
When adding apis in the manifest file like:
```
packages:
    __CNA_PACKAGE__:
      actions:
        [....]
      apis:
         hello-get
           greet:
             byname:
               hello:
                 method: GET
                   response: http
```
and then running `aio cna deploy -av` only shows the URL to the web actions

**Describe the solution you'd like**
It would be great to also have a URL to the rest api endpoint if specified in the manifest
e.g. https://NAMESPACE.adobeioruntime.net/apis/greet/byname
