### ISSUE TITLE
-a action deploy filter flag doesn't play well with multi package support

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-cli-plugin-app#366]
manifest.yml
```
packages:
  custom-package:
    license: Apache-2.0
    actions:
      generic:
        function: actions/generic/index.js
        web: 'yes'
        runtime: 'nodejs:12'
        inputs:
          LOG_LEVEL: debug
        annotations:
          require-adobe-auth: true
          final: true
      generic2:
        function: actions/generic/index.js
        web: 'yes'
        runtime: 'nodejs:12'
        inputs:
          LOG_LEVEL: debug
        annotations:
          require-adobe-auth: true
          final: true
  custom-package2:
    license: Apache-2.0
    actions:
      generic3:
        function: actions/generic/index.js
        web: 'yes'
        runtime: 'nodejs:12'
        inputs:
          LOG_LEVEL: debug
        annotations:
          require-adobe-auth: true
          final: true
      generic4:
        function: actions/generic/index.js
        web: 'yes'
        runtime: 'nodejs:12'
        inputs:
          LOG_LEVEL: debug
        annotations:
          require-adobe-auth: true
          final: true
```

cmd `aio app deploy -a custom-package/generic  --skip-static`:
```
✔ Building actions
Build success, your actions are ready to be deployed 👌
✔ Deploying actions
Your deployed actions:
  -> custom-package/__secured_generic
  -> https://23294-testprojectdeleteme-hola.adobeio-static.net/api/v1/web/custom-package/generic
```
=> OK

cmd `aio app deploy -a generic  --skip-static`:
```
✔ Building actions
Build success, your actions are ready to be deployed 👌
✔ Deploying actions
Your deployed actions:
Well done, your actions are now online 🏄
```

Action generic should be deployed even if referenced only with action name instead of <pkg>/<action>
