### ISSUE TITLE
0 values in manifest.yaml interpreted as "false" 

### ISSUE THREAD

**Issue by ackoch** [adobe/aio-cli-plugin-app#391]
**Describe the bug**

when my manifest contains 

```
    triggers:
      suppliers-import-products:
        feed: /whisk.system/alarms/interval
        inputs: 
          minutes: 5
          START_FOLDER: 'suppliers/'
          TARGET_FOLDER: '/content/dam/suppliers-import-products/'
          ARCHIVE_FOLDER_LEVEL: 0
```

I get and error

```
$ aio app deploy
Error: Please provide correct input array with key and value params in each array item
```

This does not occur on values > 0 or when I use '0'. So I believe there is some `if(value) ...` that evaluates the 0 to a false

**Expected behavior**
Treat 0 as a number

**Version**
@adobe/aio-cli-plugin-app 6.1.0 (core)
