### ISSUE TITLE
bug: specifying action limits in the manifest is not working

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-app#507]
## The Openwhisk manifest spec:
https://github.com/apache/openwhisk-wskdeploy/blob/master/specification/html/spec_actions.md#valid-limit-keys

## The manifest spec keys we care about that are supported in the Openwhisk API are:
1. timeout
2. memorySize
3. logSize
4. concurrentActivations 

## However, the Openwhisk API only supports these keys:
1. timeout
2. memory
3. logs
4. concurrency

## Repro
Deploy an action with this manifest:
```
application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      my-package:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            annotations:
              require-adobe-auth: false
              final: true
            limits:
              concurrentActivations: 300
```
Then run:
```
$ aio app deploy
$ aio rt action get my-package/generic
```
Note that the action metadata output will not show `concurrency` set to `300`.

## Workaround

For the action limits, use these keys for the corresponding `limits` keys in the spec:
1. timeout
2. memory
3. logs
4. concurrency

## Fix

Before the config is passed to the Openwhisk client library, the `limits` keys need to be mapped accordingly (see above)
