### ISSUE TITLE
Not all missing files errors are because of not running in a valid root folder.

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-cli-plugin-app#646]
E.g. point to a non existing action file path in `runtimeManifest`'s action `function` field.

```yaml
application:
  runtimeManifest:
    packages:
      mypackage:
        actions:
           mywrongaction:
             function: 'wrong/action/path.js'
```

```bash
➜  aio app deploy
✖ Building actions for 'application'
 ›   Error: Not a valid application root folder.
 ›   Please run 'aio app' commands from a folder generated by aio app init
 ›   ENOENT: no such file or directory, lstat '<wrong action path>'
```

## Proposed solution

Do not [wrap the configuration error in the app plugin](https://github.com/adobe/aio-cli-plugin-app/blob/master/src/BaseCommand.js#L37-L47), instead output a clear error directly from the [config parsing lib](https://github.com/adobe/aio-cli-lib-app-config)
