### ISSUE TITLE
web action does not have `web` in the url, resulting in an invalid link

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-app#823]
## Description

A web action does not have `web` in the url reported by the CLI, thus when calling it, it is treated as a non-web action and requires auth.

Might be relevant: 
1. the `web-export` annotation is in the wrong place
2. the `web-custom-options` annotation is present

## Expected

The web action url reported by the CLI has a valid web url.

## Actual

The web action url reported by the CLI does not have a valid web url.

## Logs for Repro

`aio app deploy` output:
```sh
$ aio app deploy
✔ Built 11 action(s) for 'application'
ℹ No frontend or a build already exists, skipping frontend build for 'application'
✔ Deployed 20 action(s) for 'application'
no frontend, skipping frontend deploy 'application'
Your deployed actions:
web actions:
...
  -> https://foo.adobeioruntime.net/api/v1/bar/init-target
...
non-web actions:
...
  -> https://foo.adobeioruntime.net/api/v1/bar/__init-target
...
```

`manifest.yaml`:
```yaml
packages:
  foobar:
    license: Apache-2.0
    actions:
      __init-target:
        function: actions/init-target/index.js
        runtime: 'nodejs:22'
        limits:
          memorySize: 1024
        annotations:
          require-adobe-auth: false
          final: true

    sequences:
      init-target:
        actions: '__init-target'
        web-export: raw
        annotations:
          web-custom-options: true
 ```

**Comment by aiojbot** [comment]
JIRA issue created: https://jira.corp.adobe.com/browse/ACNA-3397

**Comment by jenssingler** [comment]
When using the incorrect config mentioned above, but downgrading the CLI to `9.3.0` it works as expected: `web` is in web-actions URL, e.g. `https://foo.adobeioruntime.net/api/v1/web/bar/init-target`.

**Comment by shazron** [comment]
I see the commit where it was working in 9.3 but not in 10.x cli - web-export must be in annotations as per spec: [https://github.com/adobe/aio-lib-runtime/commit/4cec293955ce3dd73331f691495bbbb561d94160#diff-3a11a46e9fc8a91f5f4a114[…]a8573e864966b8f088c46faR1952](https://github.com/adobe/aio-lib-runtime/commit/4cec293955ce3dd73331f691495bbbb561d94160#diff-3a11a46e9fc8a91f5f4a1148024406fe96fd29d0aa8573e864966b8f088c46faR1952) (but I don't think it's the whole picture since it did file it under the web actions section)

**Comment by jenssingler** [comment]
I poked around with incorrect configs and 10.3.1 CLI versions - I have these 4 permutations of sequences:
```yml
      first:
        actions: '__first'
        web-export: raw
        annotations:
          web-custom-options: true
      second:
        actions: '__second'
        web-export: raw
        web: true
        annotations:
          web-custom-options: true
      third:
        actions: '__third'
        annotations:
          web-custom-options: true
          web-export: raw
      fourth:
        actions: '__fourth'
        web: true
        annotations:
          web-custom-options: true
          web-export: raw
```
This is the CLI output:
```
web actions:
  -> https://foo.adobeioruntime.net/api/v1/bar/first
  -> https://foo.adobeioruntime.net/api/v1/web/bar/second
  -> https://foo.adobeioruntime.net/api/v1/web/bar/fourth
non-web actions:
  -> https://foo.adobeioruntime.net/api/v1/web/bar/third
```
Aside from using incorrect configs, there are some oddities in the output:
`first` is listed under "web-actions", but does not contain the `web` in the URL.
`third` is listed under "non-web actions", but does contain the `web` in the URL.
